# Generated by Django 5.2.17 on 2026-09-07 17:05

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo curto entregue ao aluno. Sem relacao com dados pessoais.', max_length=6, unique=True, validators=[students.models.validate_code_format])),
                ('group', models.CharField(choices=[('pilot', 'Piloto (usa o aplicativo)'), ('control', 'Controle (nao usa o aplicativo)')], help_text='Piloto ou controle. Definido na geracao dos codigos.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['group', 'code'],
            },
        ),
    ]
