# Generated by Django 5.2.17 on 2026-09-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0002_curriculumrelease_question_count_question'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sessions', to='domain.curriculumrelease')),
                ('goal_item', models.ForeignKey(blank=True, help_text='Objetivo declarado pelo aluno, usado no desempate da recomendacao.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='domain.knowledgeitem')),
                ('resulting_state', models.ForeignKey(blank=True, help_text='Estado estimado. Vazio enquanto o teste nao converge.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sessions', to='domain.knowledgestate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='students.student')),
            ],
            options={
                'verbose_name': 'sessao de teste',
                'verbose_name_plural': 'sessoes de teste',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('position', models.PositiveSmallIntegerField(help_text='Ordem da questao dentro da sessao, a partir de 1.')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='domain.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.assessmentsession')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'ordering': ['session', 'position'],
                'constraints': [models.UniqueConstraint(fields=('session', 'question'), name='unique_response_per_question'), models.UniqueConstraint(fields=('session', 'position'), name='unique_position_per_session')],
            },
        ),
    ]
