# Generated by Django 5.2.17 on 2026-09-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('domain', '0003_question_purpose'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pre_test', 'Pré-teste aberto'), ('activity', 'Atividade (piloto usa o app)'), ('post_test', 'Pós-teste aberto'), ('closed', 'Encerrado')], default='pre_test', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracao do estudo',
                'verbose_name_plural': 'configuracao do estudo',
            },
        ),
        migrations.CreateModel(
            name='InstrumentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', 'Pré-teste'), ('post', 'Pós-teste')], max_length=4)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrument_sessions', to='domain.curriculumrelease')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_sessions', to='students.student')),
            ],
            options={
                'verbose_name': 'aplicacao do instrumento',
                'verbose_name_plural': 'aplicacoes do instrumento',
                'ordering': ['student', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_responses', to='domain.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.instrumentsession')),
            ],
            options={
                'verbose_name': 'resposta do instrumento',
                'verbose_name_plural': 'respostas do instrumento',
                'ordering': ['session', 'question__position'],
            },
        ),
        migrations.AddConstraint(
            model_name='instrumentsession',
            constraint=models.UniqueConstraint(fields=('student', 'phase'), name='unique_instrument_session_per_phase'),
        ),
        migrations.AddConstraint(
            model_name='instrumentresponse',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_instrument_response_per_question'),
        ),
    ]
