# Generated by Django 5.2.17 on 2026-09-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_studysettings_per_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentsession',
            options={'ordering': ['-started_at', '-pk'], 'verbose_name': 'sessao de teste', 'verbose_name_plural': 'sessoes de teste'},
        ),
        migrations.AlterModelOptions(
            name='instrumentresponse',
            options={'ordering': ['session', 'question__position', 'pk'], 'verbose_name': 'resposta do instrumento', 'verbose_name_plural': 'respostas do instrumento'},
        ),
    ]
