# Generated by Django 5.2.17 on 2026-09-07 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('checksum', models.CharField(help_text='SHA-256 do arquivo JSON.', max_length=64)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('state_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'versao do curriculo',
                'verbose_name_plural': 'versoes do curriculo',
                'ordering': ['-loaded_at'],
                'get_latest_by': 'loaded_at',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='1 a 5. Usado para ordenar itens dentro do topico.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='domain.knowledgeitem')),
            ],
            options={
                'verbose_name': 'item de conhecimento',
                'verbose_name_plural': 'itens de conhecimento',
                'ordering': ['topic__position', 'position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(unique=True)),
                ('size', models.PositiveSmallIntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, related_name='states', to='domain.knowledgeitem')),
            ],
            options={
                'verbose_name': 'estado de conhecimento',
                'verbose_name_plural': 'estados de conhecimento',
                'ordering': ['size', 'signature'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('bncc_skills', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='domain.topic')),
            ],
            options={
                'verbose_name': 'topico',
                'verbose_name_plural': 'topicos',
                'ordering': ['position', 'code'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domain.topic'),
        ),
    ]
