# Generated by Django 5.2.17 on 2026-09-08 16:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumrelease',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('statement', models.TextField()),
                ('alternatives', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('difficulty', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='domain.knowledgeitem')),
            ],
            options={
                'verbose_name': 'questao',
                'verbose_name_plural': 'questoes',
                'ordering': ['item__topic__position', 'item__position', 'position', 'code'],
            },
        ),
    ]
