# Generated by Django 5.2.17 on 2026-09-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_curriculumrelease_question_count_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='purpose',
            field=models.CharField(choices=[('adaptive', 'Teste adaptativo (banco do app)'), ('instrument', 'Pré/pós-teste (instrumento de pesquisa)')], default='adaptive', max_length=12),
        ),
    ]
