# Generated by Django 5.2.17 on 2026-09-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_question_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumrelease',
            options={'get_latest_by': ['loaded_at', 'pk'], 'ordering': ['-loaded_at', '-pk'], 'verbose_name': 'versao do curriculo', 'verbose_name_plural': 'versoes do curriculo'},
        ),
    ]
